import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "@/components/header";
import Sidebar from "@/components/side-bar";
import { Toaster } from "react-hot-toast";
import CreateEventDrawer from "@/components/create-event";
import { checkUser } from "@/lib/checkUser";
import ServiceWorkerProvider from "@/components/service-component";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Meet'io",
  manifest: "/manifest.json",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const user = await checkUser();
   
  console.log("DB user:", user);
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster position="bottom-right" reverseOrder={false} />
          <Header />
          <main>
            <Sidebar />
            <div className="flex-1">{children}</div>
          </main>
          {/* <main className="min-h-screen flex bg-gradient-to-b from-blue-50 to-white">
          </main> */}

          {/* <footer className="bg-blue-100 py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p>Arya2025</p>
            </div>
          </footer> */}
          <CreateEventDrawer/>
                <ServiceWorkerProvider />
        </body>
      </html>
    </ClerkProvider>
  );
}
